stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""
  PUBLIC_PATH: /api/docs

.build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${DOCKER_IMAGE} --build-arg PUBLIC_PATH=${PUBLIC_PATH} --no-cache .
    - docker push ${DOCKER_IMAGE}
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.1

  script:
    - sed -i "s#<DOCKER_IMAGE>#${DOCKER_IMAGE}#g" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service-node.yaml

# Template to deploy to staging, internal, prod
.deploy-wp:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.1

  script:
    - sed -i "s#<DOCKER_IMAGE>#${DOCKER_IMAGE}#g" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml

# Template to deploy to dev (Review apps) using kustmoize
.deploy-wp-kstmz:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.3

  script:
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize build . | kubectl apply -f -

# Template to deploy to staging, internal, prod
.deploy-newk8s:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.6
  script:
    - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - git -C ensembl-k8s-manifests/ checkout k8s123-migration
    - cd ensembl-k8s-manifests/help-and-docs
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kubectl apply -k ./

.deploy-template: &deploy-rules
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "main"'
      when: always

# Template to deploy to dev (Review apps)
.deploy-wp-review:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.3

  before_script:
    - cd k8s/overlays/review

  script:
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kustomize edit add label -f environment:${CI_COMMIT_REF_SLUG}
    - kustomize build . | kubectl apply -f -

build:
  extends: .build

# Default help-and-docs api deployment used by all ensembl-client review branches
Dev:
  extends: .deploy-wp-kstmz
  environment:
    name : wp-hx-dev
  before_script:
    - cd k8s/overlays/development
    - kustomize edit add label -f environment:dev
  only:
  - main

# Custom help-and-docs api deployment for any development branch of the api
Review:
  extends: .deploy-wp-review
  environment:
    name : wp-hx-dev
  except:
  - main


# Job to deploy to staging environment (WP-HX k8s cluster)
Staging:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-staging
  only:
  - main


# Job to deploy to staging environment (WP-HH k8s cluster)
Staging:WP-HH:
  extends: .deploy-wp
  environment:
    name : wp-hh-staging
  only:
  - main


# Job to deploy to internal environment (WP-HX k8s cluster)
Internal:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-internal
  only:
  - main

# Job to deploy to internal environment (WP-HH k8s cluster)
Internal:WP-HH:
  extends: .deploy-wp
  environment:
    name : wp-hh-internal
  only:
  - main

# Job to deploy to live environment (WP-HX k8s cluster)
Live:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-live
  only:
  - main

# Job to deploy to live environment (WP-HH k8s cluster)
Live:WP-HH:
  extends: .deploy-wp
  environment:
    name : wp-hh-live
  only:
  - main

Live:WP40:HL:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp40-hl-prod

Live:WP41:HX:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp41-hx-prod

Staging:WP40:HL:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp40-hl-staging

Internal:WP40:HL:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp40-hl-internal

Dev:WP40:HL:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp40-hl-development

Dev:WP41:HX:
  extends: .deploy-newk8s
  <<: *deploy-rules
  environment:
    name: wp41-hx-development
