stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""
  PUBLIC_PATH: /api/docs

.build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${DOCKER_IMAGE} --build-arg PUBLIC_PATH=${PUBLIC_PATH} --no-cache .
    - docker push ${DOCKER_IMAGE}
    - docker rmi ${DOCKER_IMAGE}
    - docker logout $CI_REGISTRY

# Template to deploy to staging, internal, prod
.deploy:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest
  script:
    - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - git -C ensembl-k8s-manifests/ checkout k8s123-migration
    - cd ensembl-k8s-manifests/help-and-docs
    - kustomize edit set image DOCKER_IMAGE=${DOCKER_IMAGE}
    - kubectl apply -k ./

.deploy-template: &deploy-rules
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "main"'
      when: always

build:
  extends: .build

Live:WP40:HL:
  extends: .deploy
  <<: *deploy-rules
  environment:
    name: wp40-hl-prod

Live:WP41:HX:
  extends: .deploy
  <<: *deploy-rules
  environment:
    name: wp41-hx-prod

Staging:WP40:HL:
  extends: .deploy
  <<: *deploy-rules
  environment:
    name: wp40-hl-staging

Internal:WP40:HL:
  extends: .deploy
  <<: *deploy-rules
  environment:
    name: wp40-hl-internal

Dev:WP51:HL:
  extends: .deploy
  <<: *deploy-rules
  environment:
    name: wp51-hl-development

