apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: ensembl-help-and-docs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ensembl-help-and-docs
    spec:
      imagePullSecrets:
        - name: ensembl-help-and-docs-pull-secret
      containers:
      - name: ensembl-help-and-docs
        image: <DOCKER_IMAGE>
        command: [ "npm", "run", "start-server" ]
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
